os: linux
dist: xenial

language: php

## Cache composer and apt downloads.
cache:
  apt: true
  directories:
    # Cache directory for older Composer versions.
    - $HOME/.composer/cache/files
    # Cache directory for more recent Composer versions.
    - $HOME/.cache/composer/files
    # Cache CI tooling cache files.
    - .cache

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - "nightly"

# Define the stages used.
stages:
  - name: sniff
  - name: test

jobs:
  fast_finish: true
  include:
    #### SNIFF STAGE ####
    - stage: sniff
      php: 7.4
      script:
        # Validate the composer.json file.
        # @link https://getcomposer.org/doc/03-cli.md#validate
        - composer validate --no-check-all --strict

        # Check the code style of the code base.
        - composer check-cs

  allow_failures:
    # Allow failures for unstable builds.
    - php: "nightly"


before_install:
  # Speed up build time by disabling Xdebug when its not needed.
  - phpenv config-rm xdebug.ini || echo 'No xdebug config.'


install:
  # Temporarily rollback the Composer version.
  # This can be removed once YoastCS 2.0.3 has been released.
  - travis_retry composer self-update 1.10.16
  # Set up environment using Composer.
  - |
    if [[ $TRAVIS_PHP_VERSION == "nightly" ]]; then
      # Not all PHPUnit dependencies have stable releases yet allowing for PHP 8.0.
      travis_retry composer install --no-interaction --ignore-platform-reqs
    else
      # Do a normal dev install in all other cases.
      travis_retry composer install --no-interaction
    fi


script:
  # Lint PHP files against parse errors.
  - |
    if [[ ${TRAVIS_PHP_VERSION:0:1} != "5" ]]; then
      composer lint
    else
      # Special case for PHP < 7.0.
      composer lint-lt71
    fi

  # Run the unit tests.
  - composer test
