os: linux
dist: xenial

language: php

## Cache composer and apt downloads.
cache:
  apt: true
  directories:
    # Cache directory for older Composer versions.
    - $HOME/.composer/cache/files
    # Cache directory for more recent Composer versions.
    - $HOME/.cache/composer/files

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - "nightly"

# Define the stages used.
stages:
  - name: test

jobs:
  fast_finish: true

  allow_failures:
    # Allow failures for unstable builds.
    - php: "nightly"


before_install:
  # Speed up build time by disabling Xdebug when its not needed.
  - phpenv config-rm xdebug.ini || echo 'No xdebug config.'


install:
  # Set up environment using Composer.
  - |
    if [[ $TRAVIS_PHP_VERSION == "nightly" ]]; then
      # Not all PHPUnit dependencies have stable releases yet allowing for PHP 8.0.
      travis_retry composer install --no-interaction --ignore-platform-reqs
    else
      # Do a normal dev install in all other cases.
      travis_retry composer install --no-interaction
    fi


script:
  # Lint PHP files against parse errors.
  - composer lint
